import { Button, Container, Box } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Digital Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="md">
          <Box display="flex">
            <Button>Hello</Button>
            <Box>
              <Button> Hello</Button>
            </Box>

            <Button variant="outline"> Hello</Button>
          </Box>
        </Container>
      </main>
    </div>
  );
}
