import { Container } from "@chakra-ui/react";
import Head from "next/head";
import Nav from "../components/Nav/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Digital Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="md">
          <Nav />
        </Container>
      </main>
    </div>
  );
}
